### ISSUE TITLE
Location data missing

### ISSUE THREAD

**Issue by quixoft** [CosmicPi/cosmicpi-daq#10]
There is no location data displayed from cosmicpi-daq.

Cosmic Event..: event_number:3 timer_frequency:41998678 ticks:8750 timestamp:113111.0401
adc[[Ch0][Ch1]: adc:[[1115, 1115, 1117, 1113, 1112, 1115, 1114, 1117], [1113, 1113, 1111, 1120, 1115, 1110, 1107, 1117]]
Time..........: uptime:22 time_string:113111 sequence_number:25

Cosmic Event..: event_number:4 timer_frequency:41998678 ticks:835927 timestamp:113111.060003
adc[[Ch0][Ch1]: adc:[[1121, 1116, 1113, 1114, 1117, 1116, 1115, 1114], [1121, 1116, 1116, 1120, 1113, 1115, 1114, 1113]]
Time..........: uptime:22 time_string:113111 sequence_number:26

Cosmic Event..: event_number:5 timer_frequency:41998678 ticks:839930 timestamp:113111.080002
adc[[Ch0][Ch1]: adc:[[1106, 1107, 1107, 1108, 1106, 1107, 1110, 1106], [1105, 1112, 1110, 1107, 1104, 1109, 1108, 1110]]
Time..........: uptime:22 time_string:113111 sequence_number:27

**Comment by juzsal** [comment]
Interesting. Will have a look. Thanks for reporting!

**Comment by quixoft** [comment]
It's only in the display, the data is there you are just missing printing it

**Comment by juzsal** [comment]
Yes, you're right. Had me worried for a minute!
