### ISSUE TITLE
How to register and identify CosmicPis?

### ISSUE THREAD

**Issue by juzsal** [CosmicPi/cosmicpi-daq#18]
We're going to need to have some kind of registration process for a new CosmicPi so that we can assign it a unique ID and associate that ID with a particular user. The ID will then be sent with each packet so we know whose detector it came from.

We talked about this a few times already, I just want to list here all the options and then discuss the best way to move forward.

Options for storing the ID:
- Text file somewhere on the SD card (could be edited by the user, causing havoc)
- Hard-coded in an EEPROM
- Others...?

Options for associating the ID to a user:
- First-boot registration via local web interface, user enters email address which gets sent to the server
- Registration at purchase time
- Others...?

**Comment by quixoft** [comment]
There is some synergy with encryption keys. But I think we should ignore it for the time being. We should remember that other providers of cosmic ray data might want to join the club. The simple thing to do is to use email addresses, like just about any other registration process on the web, with the usual check where a link is sent to the supplier email for verification.

**Comment by pingud98** [comment]
Evening chaps,

Thanks for raising the point Justin! I think we also need to consider that
one person might have multiple pi's. My preferred solution is:

First boot registration with a split procedure:
1) I bought my Cosmic Pi, the number on the box was X.
2) I built my Cosmic Pi, or other detector of sorts and want to connect it
to your network, in which case we'll need to assign them a number, from a
different set of numbers to the manufactured units.

If we do it this way the number will be stored on the SD card, and yes
therefore be editable. I think it's enough to say 'do not edit, it will
mess up your data and possibly everyone else's too' at the top of the file,
if someone does swap their number over I'm sure it'll be fairly apparent
from IP addresses. We should also put some friendly messages on a pi status
board per unit number/etc. as we discussed. A simple webpage should be
plenty, we don't need to develop our own two way feedback protocol.

Advantages: Lightweight, no extra hardware needed. Open to non-manufactured
devices in a relatively free way. Doesn't need us to store emails for the
devices along with their numbers.

Disadvantages: Needs web glue to hold it together. Users might screw it up.

Just my thoughts!

James

**Comment by quixoft** [comment]
It would be nice if we could just copy an image to the sd without doing anything special. I would suggest that on start up it would obtain it's id somehow. So we could just have a pile of sd cards. Also of the id is wiped it's easy to get it back. Sd cards fail. We may distribute the software via down load.

**Comment by pingud98** [comment]
Fair point Julian, though if the SD card fails the unit is 99% going to
need fully setting up again anyway as it will have forgotten the WiFi
credentials for connection.

That aside, here's a hybrid idea I came up with at lunch:

1) First log on registration (because it's needed anyway to set up wifi)
2) Enter a unique number (off the box or generated online if you built your
own)
3) Pair this number with the device MAC (for the ethernet adapter in use,
and/or the MAC for the wired one/first one to show up as eth0) in our server
4) Stamp the packets with the MAC address (I guess it's actually in there
somewhere, or we can explicitly add them on the Pi?)

If the device gets wiped and reconnects, then we can query the mac address
first off and retrive the reference number without any user action required.

Note - No database of unit number and email addresses, as previously
discussed we don't 100% need it so why risk storing it.

Uniqueness of MAC addresses:
http://www.howtogeek.com/228286/how-is-the-uniqueness-of-mac-addresses-enforced/

**Comment by quixoft** [comment]
I am not sure what you are dating on point 3. It's wlan0 or eth0. The ip address is on the packet but not the mac as far as I know so you would need to do that explicitly

**Comment by quixoft** [comment]
Saying

**Comment by pingud98** [comment]
Aha, I've been brushing up on my understanding of IP, apparently the MAC is
in the frame, and the packet is in the frame too? Anyway how about this:

1) explicitly retrive the eth0 address via python and stick this in as the
unique reference
2) if no eth0 fail-over to wlan0 for the MAC source - only applies to
people using a PiZero or an A+

3) have a more human friendly name somewhere on the server for the mac
address to relate to.

**Comment by quixoft** [comment]
Lots of isps assign dynamic ip addresses.

On Tue, May 17, 2016, 19:14 James Devine notifications@github.com wrote:

> Aha, I've been brushing up on my understanding of IP, apparently the MAC is
> in the frame, and the packet is in the frame too? Anyway how about this:
> 
> 1) explicitly retrive the eth0 address via python and stick this in as the
> unique reference
> 2) if no eth0 fail-over to wlan0 for the MAC source - only applies to
> people using a PiZero or an A+
> 
> 3) have a more human friendly name somewhere on the server for the mac
> address to relate to.
> 
> On 17 May 2016 at 18:59, Julian Lewis notifications@github.com wrote:
> 
> > Saying
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/CosmicPi/cosmicpi-daq/issues/18#issuecomment-219783487>
> 
> —
> You are receiving this because you commented.
> 
> Reply to this email directly or view it on GitHub
> https://github.com/CosmicPi/cosmicpi-daq/issues/18#issuecomment-219787807
> 
> ## 

Julian Lewis
Mobile: +33646447515

**Comment by quixoft** [comment]
Sorry, must get out of the habit of replying via email. Are you sure the router translation from lan address to wan address sends the mac. The router users a random high port number on the outside and translated that back to your lan port and ip. Why should or send on the mac address.

**Comment by juzsal** [comment]
As far as I understand from what you guys are saying, we can just set the MAC address explicitly in our packet payload. It can be retrieved from python like this (copied from StackOverflow):

``` python
def getHwAddr(ifname):
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    info = fcntl.ioctl(s.fileno(), 0x8927,  struct.pack('256s', ifname[:15]))
    return ':'.join(['%02x' % ord(char) for char in info[18:24]])

print getHwAddr('eth0')
```

**Comment by quixoft** [comment]
Yes that would work, I was just surprised that mac addresses are forwarded over routers. That's horrible, if true, there would be no way to hide. However just putting it explicitly in the packet would make a good id, as long as you don't change your wifi dongle.

**Comment by juzsal** [comment]
Could we collect both eth0 and wlan0? If the wifi dongle changes, wlan0 would change but eth0 probably wouldn't. So it might be more reliable. On a Pi Zero, it would always be wlan0 and it would never change since it's built in, right? (I'm completely guessing, I don't have a Zero to check that)

**Comment by quixoft** [comment]
Yes we could do that. But the idea of using mac address might not be as good as say, just asking the user to enter a password once. So when he starts up the pi says give me a password and if it's not already taken then that's it. Why use mac addresses ? Any old fixed number will do, and there is coupling between things that don't need coupling. There could perhaps be a virtual cosmic ray detector with no mac address. Who knows.

**Comment by juzsal** [comment]
I agree, any old fixed number will do, it's just that we need to store that number on the Pi in a persistent way, right? And the MAC address is hard-coded into the hardware, so even if the SD card gets wiped I guess we'll still be able to identify the Pi.

**Comment by quixoft** [comment]
If the sd gets wiped then re register, login vs sign-up.  It's what happens on just about every app on my phone. Why do we neneed to do our own thing.Why not use the same method as every one else ? All you need to do is store the number. I don't see any advantage using mac, and there could be problems with hardware changed or upgraded for no valid reason

**Comment by juzsal** [comment]
But isn't that more hard work for the user? Also, WhatsApp, Viber etc. only require a phone number (which is hard-coded in the SIM and roughly as unique as a MAC address). No passwords.

**Comment by quixoft** [comment]
Not really, all he has to do is invent a password and remember it, if he forgets then he should register a new one. It's not exactly rocket science, what would happen if he changed his wifi dongle ? Same thing. Coupling mac addresses to user I'd isn't without problems, they weren't intended for that. That's my gut feeling, instinct...

**Comment by pingud98** [comment]
Morning all,

Just to close the circle - we started off looking for a way to uniquely
identify each device in a persistent manner, so that you wouldn't have to
re-register in case of an SD card crash.

We've got a built in, unique number/method with the MAC. Let's use it:

If we have eth0 let's use that, it's least likely to change.
If we don't have eth0 then let's use wlan0 in this case.
Realistically the B+ or the 3 is our target platform, where eth0 and wlan0
are both onboard and fixed.

Use case 1 - pi connected over wired ethernet, SD crash and re-image; works
first time.
Use case 2 - pi dies, pi replaced, need to re-index it with the new ID at
first login so that we can link the data recorded with the old MAC.
Use case 3 - wifi dongle dies/fails/is changed - assuming we have an Eth0,
no impact at all.

Julian, I know that a simple username or just password would be easy and
more conventional. It also has the advantage of being hardware agnostic.
However, if we can avoid storing any user data, let's avoid storing any
user data. It's just a liability waiting to get stolen. There's no need for
us to store usernames, passwords or email addresses.

We just need to be able to tell the difference between our devices, we have
a way that's simple lightweight and doesn't give the user an opportunity to
screw things up or forget.

Is this ok or shall we discuss it over coffee later this week?

James

**Comment by quixoft** [comment]
Ok no problem, I guess it's good to play devil's advocate during brain
storming. One last thing.... What about people who don't use a pi, for
example people who just connect the Arduino straight to their pc. Then
there may be problems accessing the mac of eth0 or whatever. It's just
better to think of what may go wrong before we adopt a method. The password
thing is platform independent, the mac address thing is not.

On Wed, May 18, 2016, 11:19 James Devine notifications@github.com wrote:

> Morning all,
> 
> Just to close the circle - we started off looking for a way to uniquely
> identify each device in a persistent manner, so that you wouldn't have to
> re-register in case of an SD card crash.
> 
> We've got a built in, unique number/method with the MAC. Let's use it:
> 
> If we have eth0 let's use that, it's least likely to change.
> If we don't have eth0 then let's use wlan0 in this case.
> Realistically the B+ or the 3 is our target platform, where eth0 and wlan0
> are both onboard and fixed.
> 
> Use case 1 - pi connected over wired ethernet, SD crash and re-image; works
> first time.
> Use case 2 - pi dies, pi replaced, need to re-index it with the new ID at
> first login so that we can link the data recorded with the old MAC.
> Use case 3 - wifi dongle dies/fails/is changed - assuming we have an Eth0,
> no impact at all.
> 
> Julian, I know that a simple username or just password would be easy and
> more conventional. It also has the advantage of being hardware agnostic.
> However, if we can avoid storing any user data, let's avoid storing any
> user data. It's just a liability waiting to get stolen. There's no need for
> us to store usernames, passwords or email addresses.
> 
> We just need to be able to tell the difference between our devices, we have
> a way that's simple lightweight and doesn't give the user an opportunity to
> screw things up or forget.
> 
> Is this ok or shall we discuss it over coffee later this week?
> 
> James
> 
> On 18 May 2016 at 00:25, Julian Lewis notifications@github.com wrote:
> 
> > Not really, all he has to do is invent a password and remember it, if he
> > forgets then he should register a new one. It's not exactly rocket
> > science,
> > what would happen if he changed his wifi dongle ? Same thing. Coupling
> > mac
> > addresses to user I'd isn't without problems, they weren't intended for
> > that. That's my gut feeling, instinct...
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/CosmicPi/cosmicpi-daq/issues/18#issuecomment-219872676>
> 
> —
> You are receiving this because you commented.
> 
> Reply to this email directly or view it on GitHub
> https://github.com/CosmicPi/cosmicpi-daq/issues/18#issuecomment-219971294
> 
> ## 

Julian Lewis
Mobile: +33646447515

**Comment by pingud98** [comment]
Point taken, if they're using a pc though it'll have either an eth0 or a
wlan0 somewhere which hopefully we can access.. if we don't have the user
level privilidges to access the MAC via linux/etc. i'm sure that can be
fixed with changing the permissions (like you have to do with +modem for
arduino for example). True you'll need sudo priviliges to make that
modification, but it shouldn't be too hard!

**Comment by quixoft** [comment]
On Windows 10 ! So that's it. I leave it to you to choose now.

**Comment by pingud98** [comment]
It should work on Windows 10? We just need a reasonable Python script that
will cope with cross platform, we have all the platforms to test it on. I
don't think an escalated level of privilidge is requires so long as you ask
the OS the right way. I also note that sometimes systems make up a fake mac
address if they can't get the real one, basically a random number with a
bitmask so you can tell it's fake if you know where to look. This could be
an issue, but let's see if it comes up.

Let's give MACs a try for the device identifier. If we find it doesn't work
as we expect, or we come up with something that's better and doesn't
require us to hold user data, I'm open to changing it in future.

We should also have a separate device number, to prevent exposing the MAC
too publically, as this would be useful for hackers doing MAC spoofing,
especially if for whatever reason we end up with the wlan0 MAC.

James

**Comment by quixoft** [comment]
Ok then let's go for that solution. Let's hope it won't bite us in the future.
